apiVersion: apps/v1
kind: Deployment

metadata:
  name: go-backend-deployment
  labels:
    app:
      go-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: antonyinjila/todo-backend
        ports:
        - containerPort: 8081
        env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_default_region

        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id

        - name: AWS_ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_secret_key

---

apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
     